worker_processes 1;

events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  sendfile on;

  limit_req_zone $binary_remote_addr zone=perip:10m rate=60r/m;

  map "$request_method $request_uri" $required_scope {
    default "";
    ~^POST\ /parking/api/spots admin;
    ~^PATCH\ /parking/api/spots/ admin;
    ~^POST\ /payments/api/pricing admin;
  }

  include /etc/nginx/conf.d/*.conf;
}
